using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

namespace Rokid.MRC
{
    public class AxisController : MonoBehaviour
    {
        private Transform axisTrans;

        public Text txtDesc;

        void Start()
        {
            axisTrans = transform.parent;
        }

        void Update()
        {
            txtDesc.text = $"Pos : {axisTrans.position} \n Rot : {axisTrans.rotation}";

            transform.rotation = Quaternion.LookRotation(Camera.main.transform.forward);
        }
    }
}